theme: jekyll-theme-cayman
description: [The replication package for Learning CNN-Encoded Propositions of Action Sequence-based Robotic Programs from Few Demonstrations]

url: "https://lceprpfd.github.io/"
is_user_page: true
github.is_user_page: true
